### PR TITLE
added support for system_info endpoint

### LINKED ISSUE #10: Support system info endpoint

### PR DESCRIPTION
**Pull request by shyam**
This will resolve #10 .

As this is my first contribution to a ruby gem, please help me on changing any specific specs to the style followed within this project.

### CODE REVIEW

**Comment by dblessing** [comment]
Thanks for contributing, @shyam. Everything looks good other than a few minor personal styling preferences. Please only make one expectation per `it` block. Also, you don't need to specify an `it` block description for all of those, which will make it a little shorter (the `expect(a_get..` requires a description because there isn't an inferred description). Don't worry about the line length comment in the specs as long as it's under 100-120.

**Comment by shyam** [comment]
thanks for the review, @dblessing. will address them and push again.

**Comment by shyam** [comment]
@dblessing - Travis had failed on account of rubocop. However, the same command passes on my local. Any ideas ?

local rubocop

**Comment by dblessing** [comment]
@shyam I've seen that before with different versions of rubocop. When running with `bundle exec` I would expect that to be resolved, but I'm not sure. I'll take a look and won't reject it just because of a small style issue :smile:

**Comment by dblessing** [comment]
@shyam Sorry for the delay. Thank you for your contribution! I will release a new gem shortly

**Comment by dblessing** [comment]
FYI - I made one slight change. I drilled the system_info object down to `system` since there's no usable info at the `system` level. Now instead of calling `Rundeck.system_info.system...` you can simply call `Rundeck.system_info.stats...` or whatever info you want.

**Comment by shyam** [comment]
Thanks Drew.

**Comment by dblessing** [comment]
Released as 1.2.0

**Pull request merged**
